// This is generated by writeCoreEval; please edit!
/* eslint-disable */

const manifestBundleRef = {bundleID:"b1-883387e11c7f2509e54d438d9c7434fca0acccecd206c9d650df5b0782f81669070a1323997debeb60451dfb73d9b214d651a685c1552d9905e251f404e73e0d"};
const getManifestCall = harden([
  "getManifest",
  {
    installationRef: {
      bundleID: "b1-8f9bb6190346934f9ca17901f34e25b78cce2fef16dd97b8c910fe3d193c3ffbe392c26e8d95518dd329c1eed7cf67f8af941bfea3c919014c39bd578fa2b522",
    },
    options: {
      assetInfo: [
        [
          "uist",
          {
            baseDenom: "uist",
            baseName: "agoric",
            chainName: "agoric",
          },
        ],
        [
          "ubld",
          {
            baseDenom: "ubld",
            baseName: "agoric",
            chainName: "agoric",
          },
        ],
        [
          "ibc/2CC0B1B7A981ACC74854717F221008484603BB8360E81B262411B0D830EDE9B0",
          {
            baseDenom: "uaxl",
            baseName: "axelar",
            brandKey: "AXL",
            chainName: "agoric",
          },
        ],
      ],
      chainInfo: {
        agoric: {
          bech32Prefix: "agoric",
          chainId: "agoricdev-25",
          connections: {
            "axelar-testnet-lisbon-3": {
              client_id: "07-tendermint-22",
              counterparty: {
                client_id: "07-tendermint-1193",
                connection_id: "connection-942",
              },
              id: "connection-19",
              state: "STATE_OPEN",
              transferChannel: {
                channelId: "channel-315",
                counterPartyChannelId: "channel-623",
                counterPartyPortId: "transfer",
                ordering: "ORDER_UNORDERED",
                portId: "transfer",
                state: "STATE_OPEN",
                version: "ics20-1",
              },
            },
            "grand-1": {
              client_id: "07-tendermint-13",
              counterparty: {
                client_id: "07-tendermint-432",
                connection_id: "connection-396",
              },
              id: "connection-13",
              state: "STATE_OPEN",
              transferChannel: {
                channelId: "channel-11",
                counterPartyChannelId: "channel-337",
                counterPartyPortId: "transfer",
                ordering: "ORDER_UNORDERED",
                portId: "transfer",
                state: "STATE_OPEN",
                version: "ics20-1",
              },
            },
          },
          namespace: "cosmos",
          reference: "agoricdev-25",
          stakingTokens: [
            {
              denom: "ubld",
            },
          ],
        },
        axelar: {
          bech32Prefix: "axelar",
          chainId: "axelar-testnet-lisbon-3",
          namespace: "cosmos",
          reference: "axelar-testnet-lisbon-3",
          stakingTokens: [
            {
              denom: "uaxl",
            },
          ],
        },
        noble: {
          bech32Prefix: "noble",
          chainId: "grand-1",
          namespace: "cosmos",
          reference: "grand-1",
          stakingTokens: [
            {
              denom: "uusdc",
            },
          ],
        },
      },
    },
  },
]);
const customManifest = {
  startAxelarGmp: {
    consume: {
      agoricNames: true,
      board: true,
      chainStorage: true,
      chainTimerService: true,
      cosmosInterchainService: true,
      localchain: true,
      startUpgradable: true,
    },
    installation: {
      consume: {
        createlcaAndGmpV3: true,
      },
    },
    instance: {
      produce: {
        createlcaAndGmpV3: true,
      },
    },
    issuer: {
      consume: {
        BLD: true,
      },
    },
  },
};

// Make a behavior function and "export" it by way of script completion value.
// It is constructed by an anonymous invocation to ensure the absence of a global binding
// for makeCoreProposalBehavior, which may not be necessary but preserves behavior pre-dating
// https://github.com/Agoric/agoric-sdk/pull/8712 .
const behavior = (({
  manifestBundleRef,
  getManifestCall: [manifestGetterName, ...manifestGetterArgs],
  customManifest,
  E,
  log = console.info,
  customRestoreRef,
}) => {
  const { entries, fromEntries } = Object;

  /**
   * Given an object whose properties may be promise-valued, return a promise
   * for an analogous object in which each such value has been replaced with its
   * fulfillment.
   * This is a non-recursive form of endo `deeplyFulfilled`.
   *
   * @template T
   * @param {{[K in keyof T]: (T[K] | Promise<T[K]>)}} obj
   * @returns {Promise<T>}
   */
  const shallowlyFulfilled = async obj => {
    if (!obj) {
      return obj;
    }
    const awaitedEntries = await Promise.all(
      entries(obj).map(async ([key, valueP]) => {
        const value = await valueP;
        return [key, value];
      }),
    );
    return fromEntries(awaitedEntries);
  };

  const makeRestoreRef = (vatAdminSvc, zoe) => {
    /** @type {(ref: import\('./externalTypes.js').ManifestBundleRef) => Promise<Installation<unknown>>} */
    const defaultRestoreRef = async bundleRef => {
      // extract-proposal.js creates these records, and bundleName is
      // the optional name under which the bundle was installed into
      // config.bundles
      const bundleIdP =
        'bundleName' in bundleRef
          ? E(vatAdminSvc).getBundleIDByName(bundleRef.bundleName)
          : bundleRef.bundleID;
      const bundleID = await bundleIdP;
      const label = bundleID.slice(0, 8);
      return E(zoe).installBundleID(bundleID, label);
    };
    return defaultRestoreRef;
  };

  /** @param {ChainBootstrapSpace & BootstrapPowers & { evaluateBundleCap: any }} powers */
  const coreProposalBehavior = async powers => {
    // NOTE: `powers` is expected to match or be a superset of the above `permits` export,
    // which should therefore be kept in sync with this deconstruction code.
    // HOWEVER, do note that this function is invoked with at least the *union* of powers
    // required by individual moduleBehaviors declared by the manifest getter, which is
    // necessary so it can use `runModuleBehaviors` to provide the appropriate subset to
    // each one (see ./writeCoreEvalParts.js).
    // Handle `powers` with the requisite care.
    const {
      consume: { vatAdminSvc, zoe, agoricNamesAdmin },
      evaluateBundleCap,
      installation: { produce: produceInstallations },
      modules: {
        utils: { runModuleBehaviors },
      },
    } = powers;

    // Get the on-chain installation containing the manifest and behaviors.
    log('evaluateBundleCap', {
      manifestBundleRef,
      manifestGetterName,
      vatAdminSvc,
    });
    let bcapP;
    if ('bundleName' in manifestBundleRef) {
      bcapP = E(vatAdminSvc).getNamedBundleCap(manifestBundleRef.bundleName);
    } else if ('bundleID' in manifestBundleRef) {
      bcapP = E(vatAdminSvc).getBundleCap(manifestBundleRef.bundleID);
    } else {
      const keys = Reflect.ownKeys(manifestBundleRef).map(key =>
        typeof key === 'string' ? JSON.stringify(key) : String(key),
      );
      const keysStr = `[${keys.join(', ')}]`;
      throw Error(
        `bundleRef must have own bundleName or bundleID, missing in ${keysStr}`,
      );
    }
    const bundleCap = await bcapP;

    const proposalNS = await evaluateBundleCap(bundleCap);

    // Get the manifest and its metadata.
    log('execute', {
      manifestGetterName,
      bundleExports: Object.keys(proposalNS),
    });
    const restoreRef = customRestoreRef || makeRestoreRef(vatAdminSvc, zoe);
    const {
      manifest,
      options: rawOptions,
      installations: rawInstallations,
    } = await proposalNS[manifestGetterName](
      harden({ restoreRef }),
      ...manifestGetterArgs,
    );

    // Await promises in the returned options and installations records.
    const [options, installations] = await Promise.all(
      [rawOptions, rawInstallations].map(shallowlyFulfilled),
    );

    // Publish the installations for our dependencies.
    const installationEntries = entries(installations || {});
    if (installationEntries.length > 0) {
      const installAdmin = E(agoricNamesAdmin).lookupAdmin('installation');
      await Promise.all(
        installationEntries.map(([key, value]) => {
          produceInstallations[key].reset();
          produceInstallations[key].resolve(value);
          return E(installAdmin).update(key, value);
        }),
      );
    }

    // Evaluate the manifest.
    return runModuleBehaviors({
      // Remember that `powers` may be arbitrarily broad.
      allPowers: powers,
      behaviors: proposalNS,
      manifest: customManifest || manifest,
      makeConfig: (name, _permit) => {
        log('coreProposal:', name);
        return { options };
      },
    });
  };

  return coreProposalBehavior;
})({ manifestBundleRef, getManifestCall, customManifest, E });
behavior;
